save_checkpoint_steps: 5000
seed: 3435
train_steps: 25000
valid_steps: 5000  
warmup_steps: 4000
report_every: 100
log_file: experiment_transformer_base.log

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.98
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 6144
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 64

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
share_decoder_embeddings: 'true'
share_embeddings: 'true'
  
# Need to define:

world_size: 4
gpu_ranks: [0, 1, 2, 3]

## tensorboard config
#tensorboard: 'true'
#tensorboard_log_dir

## path to the data and saved model

# data:
# save_model: 
# val_result_file: 
